### ISSUE TITLE
Error: kustomize could not be found ./install.sh: line 42: tmp_dir: unbound variable

### ISSUE THREAD

**Issue by ayyubibrahimi** [pckhoi/k8s-ocr-jobqueue#1]
Hi @pckhoi I'm receiving the following error message when I attempt to install k8s-ocr-jobqueue on the new computer. Please advise. Thanks.

```
Error: kustomize could not be found
./install.sh: line 42: tmp_dir: unbound variable
```

**Comment by pckhoi** [comment]
The job queue is already installed on Kubernetes so you don't need to
install anything. Just installing python packages is enough.

**Comment by ayyubibrahimi** [comment]
Ok. Thanks.
